language: java

jdk:
  - oraclejdk7
#  - oraclejdk8
  
os:
  - linux

sudo: false

install: true

script: mvn clean test

after_success:
  - mvn -Pwith-covers clean test jacoco:report coveralls:report

branch:
  only:
    - master

notifications:
  email:
    - bak723@gmail.com

