language: java

jdk:
  - oraclejdk7

os:
  - linux

sudo: false

install: true

script: ./mvnw clean test

after_success:
  - ./mvnw -Pwith-covers clean test jacoco:report coveralls:report

branch:
  only:
    - master

notifications:
  email:
    - bak723@gmail.com
    - syjsmk@naver.com