language: java

jdk:
  - oraclejdk7
  - oraclejdk8
  
os:
  - linux

sudo: false

install:
  - "cd tools/jrat; ./gradlew install; cd -"
  - "cd tools/spring-social-github; ./gradlew install; cd -"

script: mvn clean test

after_success:
  - mvn -Pwith-covers clean test jacoco:report coveralls:report

branch:
  only:
    - master

notifications:
  email:
    - bak723@gmail.com

