language: java
jdk:
  - oraclejdk6
  - oraclejdk7
  
os:
  - linux
  
install: /bin/true
  
before_script:
  - "cd tools/jrat; ./gradlew install; cd -"
  - "export PATH=`pwd`/tools/travis:$PATH"

script: mvn test

branch:
  only:
    - master

notifications:
  email:
    - bak723@gmail.com

