spring:
  mvc:
    locale: ko_KR
  freemarker:
    requestContextAttribute: rc
  datasource:
    schema: classpath:/org/springframework/social/connect/jdbc/JdbcUsersConnectionRepository.sql
    continueOnError: true
  jpa:
    openInView: true
    show-sql: true
    generate-ddl: true
  hibernate:
    ddl-auto: update
  social.github:
    appId: dd1c3e0040b33db36c35
    appSecret: 87fc2c47acdd073908fc1c1a76cee50d23877c0e
security:
  ignored: true
  basic.enabled: false
sky:
  curator:
    namespace: SkyEngine
    retryTime: 100

# Logging
logging.level.com.sky: TRACE