spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:sky
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
  hibernate:
    ddl-auto: create-drop
  social.github:
    appId: dd1c3e0040b33db36c35
    appSecret: 87fc2c47acdd073908fc1c1a76cee50d23877c0e
sky:
  curator:
    connections: localhost:32181

logging.level:
  com.sky: TRACE
