spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:sky
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
sky:
  curator:
    connections: localhost:32181

logging.level:
  com.sky: TRACE
